import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { Toaster } from "react-hot-toast";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";
import localFont from "next/font/local";

// Define local font
const poppins = localFont({
  src: "./fonts/Poppins-Regular.woff2",
  variable: "--font-poppins",
  weight: "400",
  preload: true, // ✅ Recommended for performance
});

export const metadata: Metadata = {
  title: "Ecommerce App for Shoppers",
  description: "Generated by create next app",
  keywords: ["ecommerce", "shopping", "nextjs", "sanity", "clerk"],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();

  return (
    <ClerkProvider>
      <html lang="en" className={poppins.variable}> {/* ✅ Set font variable here */}
        <body className="antialiased">
          {isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          {children}
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#000",
                color: "#fff",
              },
            }}
          />
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
